# Fly.io application configuration
app = "mkto-backend"
primary_region = "iad"

[build]

[env]
  ENVIRONMENT = "production"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/health"
  port = 8000
  timeout = "5s"
  type = "http"

[http_service.concurrency]
  type = "requests"
  hard_limit = 100
  soft_limit = 80

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8000"

[mounts]
  source = "mkto_data"
  destination = "/data"
