#!/bin/bash

echo "🚀 MKTO Portfolio Optimization Platform"
echo "======================================"
echo ""
echo "✅ Completed Setup:"
echo "  - React frontend with Tailwind CSS"
echo "  - FastAPI backend with portfolio optimization"
echo "  - Knapsack algorithm implementation"
echo "  - API integration between frontend and backend"
echo "  - Modern UI with interactive components"
echo ""
echo "🛠️ To Start Development:"
echo ""
echo "1. Start Backend:"
echo "   cd /workspaces/MKTO"
echo "   /workspaces/MKTO/.venv/bin/python -m uvicorn app.simple_main:app --host 0.0.0.0 --port 8000 --reload &"
echo ""
echo "2. Start Frontend:"
echo "   npm run dev &"
echo ""
echo "3. Open Application:"
echo "   Frontend: http://localhost:5173"
echo "   Backend API: http://localhost:8000"
echo "   API Docs: http://localhost:8000/docs"
echo ""
echo "🎯 Features Ready:"
echo "  ✅ Asset selection with smart suggestions"
echo "  ✅ Budget control with interactive gauge"
echo "  ✅ Risk tolerance selection (Conservative/Balanced/Aggressive)"
echo "  ✅ Portfolio optimization using knapsack algorithm"
echo "  ✅ Results display with flip card animations"
echo "  ✅ Real-time API integration"
echo ""
echo "🔗 Test API Endpoints:"
echo "  GET  /health                    - Health check"
echo "  GET  /api/v1/assets            - Available assets"
echo "  POST /api/v1/optimize          - Portfolio optimization"
echo "  GET  /api/v1/portfolio         - Current portfolio"
echo ""
echo "Happy optimizing! 📈"
